- name: load files
  include: installer_files.yaml
- name: install portworx
  include: portworx_install.yaml
- name: update registry deployment
  include: registry_setup.yaml
- name: load assembly installer
  include: lite_install.yaml
- name: load wsl installer
  include: wsl_install.yaml
  when: wsl_install is True
- name: load wkc installer
  include: wkc_install.yaml
  when: wkc_install is True