- name: extract docker registry
  command: oc get routes docker-registry -n default -o template=\{\{.spec.host}}
  register: docker_registry
- name: get token
  command: oc whoami -t
  register: oc_token
- name: Run wkc adm setup
  command: bin/cpd-linux adm -r repo.yaml -a wkc -n {{namespace}} --apply --accept-all-licenses 
  args:
    chdir: /opt/cp4d
- name: Run wkc install
  command: |
    bin/cpd-linux
    -r repo.yaml
    -a wkc
    -n {{namespace}}
    -c portworx-shared-gp
    -o cpd-portworx/overrides/wkc-override.yaml
    --transfer-image-to {{docker_registry.stdout}}/{{namespace}}
    --cluster-pull-prefix docker-registry.default.svc:5000/{{namespace}}
    --target-registry-username ocadmin
    --target-registry-password {{oc_token.stdout}}
    --accept-all-licenses
    --insecure-skip-tls-verify
  args:
    chdir: /opt/cp4d
- name: Run wkc patch 1
  command: |
    bin/cpd-linux
    -r repo.yaml
    -a wkc
    -n {{namespace}}
    --patch-name cpd-2.5.0.0-ccs-patch-5
    --transfer-image-to {{docker_registry.stdout}}/{{namespace}}
    --cluster-pull-prefix docker-registry.default.svc:5000/{{namespace}}
    --target-registry-username ocadmin
    --target-registry-password {{oc_token.stdout}}
    --accept-all-licenses
    --insecure-skip-tls-verify
  args:
    chdir: /opt/cp4d
  when: wkc_patch is true
- name: Run wkc patch 2
  command: |
    bin/cpd-linux
    -r repo.yaml
    -a wkc
    -n {{namespace}}
    --patch-name wkc-patch-3.0.0.6
    --transfer-image-to {{docker_registry.stdout}}/{{namespace}}
    --cluster-pull-prefix docker-registry.default.svc:5000/{{namespace}}
    --target-registry-username ocadmin
    --target-registry-password {{oc_token.stdout}}
    --accept-all-licenses
    --insecure-skip-tls-verify
  args:
    chdir: /opt/cp4d
  when: wkc_patch is true
- name: apply patch file
  command: oc patch deployment wkc-glossary-service -n {{namespace}} -p "$(cat /opt/installer/roles/wkc_configure/files/wkc_glossary_service_patch.yaml)"